### ISSUE TITLE
请问博主后续还会更新吗？

### ISSUE THREAD

**Issue by zearoby** [korimas/PyQTerminal#1]
尊敬的博主，你好:

我之前找了好久类似的软件，最后找到你的这个程序，感觉到非常的好用，因此送上了一个星星，谢谢博主带来的优质软件。
我在源代码中看到还有很多的TODO未完成，由于本人是一个业余的python爱好者，没有能力来优化这些TODO，而且很多代码看不懂什么意思，请问博主后续还会更新吗？非常感谢。

祝好

**Comment by korimas** [comment]
这是个半成品，性能也不太好，有些问题暂时不太好解决，后面找到好的方案会更新

**Comment by zearoby** [comment]
期待博主更优秀的作品，谢谢你。
